language: python

python:
    - '2.7'
    - '3.4'
    - '3.5'
    - '3.6'
    - 'pypy'

install:
    - 'pip install --upgrade -r requirements.txt'
    - 'pip install --upgrade -r requirements_test.txt'

matrix:
  include:
  - python: '3.6'
    env: TEST_ENDPOINTS=True


script:
    - 'python setup.py test'
    - '[[ ! - z $TEST_ENDPOINTS ]] && python tests/test_api_endpoints.py'
